var __slice = Array.prototype.slice;

/**
 * createTimeEndpoint is a helper method to generate instance methods for
 * SummaryService and StoryLineService. It returns a function that completes a
 * request to the path generated by createPath.
 * @param {Function} createPath
 * @return {Function} function(args..., opts, cb)
 */
exports.createTimeEndpoint = function (createPath) {
  return function () {
    var pathArity = createPath.length;
    var pathArgs = __slice.call(arguments, 0, pathArity);
    var path = createPath.apply(null, pathArgs);
    var cb, opts;
    var arglen = arguments.length;
    if (arglen === pathArity + 1) {
      opts = {};
      cb = arguments[arglen-1];
    } else {
      opts = arguments[arglen-2];
      cb= arguments[arglen-1];
    }
    this.client._request(path, opts, cb);
  };
};

exports.createPastDaysEndpoint = function (pathPrefix) {
  return function (days, opts, cb) {
    if (arguments.length === 2) {
      cb = opts;
      opts = {};
    }
    opts.pastDays = days;
    this.client._request(pathPrefix, opts, cb);
  };
};

exports.doubleDigit = function (num) {
  return (num < 10) ? ("0" + num) : String(num);
};

exports.DateRangeService = DateRangeService;

function DateRangeService(client, pathPrefix) {
  this.client = client;
  this.pathPrefix = pathPrefix;
}

DateRangeService.prototype.from = function (year, month, day) {
  this._from = year + doubleDigit(month) + doubleDigit(day);
  return this;
};

DateRangeService.prototype.to = function (year, month, day, opts, cb) {
  if (arguments.length === 4) {
    cb = opts;
    opts = {};
  }
  opts.from = this._from;
  opts.to = year + doubleDigit(month) + doubleDigit(day);
  var path = this.client._request(this.pathPrefix, opts, cb);
};
